const items = [
	{
		pid: 1,
		img: "assets/img/p1.png",
		name: "red hoodie",
		color: "red",
		stock: true,
		price: 30.0,
		category: "hoodies",
		totalQty: 100,
		size: ["xs", "s", "m", "l", "xl"],
	},
	{
		pid: 2,
		img: "assets/img/p2.png",
		name: "black hoodie",
		color: "black",
		stock: true,
		price: 30.0,
		category: "hoodies",
		totalQty: 100,
		size: ["xs", "s", "m", "l", "xl"],
	},
	{
		pid: 3,
		img: "assets/img/p3.png",
		name: "white hoodie",
		color: "white",
		stock: true,
		price: 30.0,
		category: "hoodies",
		totalQty: 100,
		size: ["xs", "s", "m", "l", "xl"],
	},
	{
		pid: 4,
		img: "assets/img/p4.png",
		name: "black pant",
		color: "black",
		stock: false,
		price: 20.0,
		category: "pants",
		totalQty: 0,
		size: ["xs", "s", "m", "l", "xl"],
	},
	{
		pid: 5,
		img: "assets/img/p5.png",
		name: "white pant",
		color: "white",
		stock: true,
		price: 20.0,
		category: "pants",
		totalQty: 100,
		size: ["xs", "s", "m", "l", "xl"],
	},
	{
		pid: 6,
		img: "assets/img/p6.png",
		name: "grey pant",
		color: "grey",
		stock: true,
		price: 20.0,
		category: "pants",
		totalQty: 100,
		size: ["xs", "s", "m", "l", "xl"],
	},
	{
		pid: 7,
		img: "assets/img/p7.png",
		name: "blue pant",
		color: "blue",
		stock: true,
		price: 20.0,
		category: "pants",
		totalQty: 100,
		size: ["xs", "s", "m", "l", "xl"],
	},
	{
		pid: 8,
		img: "assets/img/p8.png",
		name: "black shirt",
		color: "black",
		stock: true,
		price: 28.0,
		category: "shirts",
		totalQty: 100,
		size: ["xs", "s", "m", "l", "xl"],
	},
	{
		pid: 9,
		img: "assets/img/p9.png",
		name: "white shirt",
		color: "white",
		stock: true,
		price: 28.0,
		category: "shirts",
		totalQty: 100,
		size: ["xs", "s", "m", "l", "xl"],
	},
	{
		pid: 10,
		img: "assets/img/p10.png",
		name: "blue shirt",
		color: "blue",
		stock: false,
		price: 28.0,
		category: "shirts",
		totalQty: 0,
		size: ["xs", "s", "m", "l", "xl"],
	},
];

module.exports = items;
